server:
  port: 8084

spring:
  application:
    name: redis-cache-service
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  cloud:
    compatibility-verifier:
      enabled: false  # ✅ ADD THIS LINE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.ecommerce.redis_cache_service: DEBUG